export const APP_NAME = 'BidWise'
export const APP_NAME_CN = '标智'

export enum ErrorCode {
  UNKNOWN = 'UNKNOWN',
  VALIDATION = 'VALIDATION',
  NOT_FOUND = 'NOT_FOUND',
  DUPLICATE = 'DUPLICATE',
  DATABASE = 'DATABASE',
  IPC = 'IPC',
  AI_PROXY = 'AI_PROXY',
  AI_PROXY_TIMEOUT = 'AI_PROXY_TIMEOUT',
  AI_PROXY_RATE_LIMIT = 'AI_PROXY_RATE_LIMIT',
  AI_PROXY_AUTH = 'AI_PROXY_AUTH',
  AI_PROXY_PROVIDER = 'AI_PROXY_PROVIDER',
  FILE_SYSTEM = 'FILE_SYSTEM',
  PARSE = 'PARSE',
  EXPORT = 'EXPORT',
  CONFIG = 'CONFIG',
  AGENT_NOT_FOUND = 'AGENT_NOT_FOUND',
  AGENT_EXECUTE = 'AGENT_EXECUTE',
  AGENT_TIMEOUT = 'AGENT_TIMEOUT',
  TASK_QUEUE = 'TASK_QUEUE',
  TASK_NOT_FOUND = 'TASK_NOT_FOUND',
  TASK_CANCELLED = 'TASK_CANCELLED',
}

export const IPC_RESPONSE_SUCCESS = true
export const IPC_RESPONSE_FAILURE = false
